### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by hashrock** [hashrock/deno-avatar#1]
It appears that the image is not cached on the browser side even if Cache-Control is returned. Why is that?

Avatar always returns the same thing for a URL, so I want the browser to use the cache.

**Comment by kidonng** [comment]
The images are correctly cached:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/44045911/186420733-cc892d7e-93ee-4d63-8cf7-4df80c83b307.png">

I guess you made the wrong assumption because you directly opened the image and kept refreshing. The image is treated as main resource this way and the browser will bust the cache (i.e. ignore cache headers), because it thinks you are refreshing to see the latest version. You can [read more on Stack Overflow](https://stackoverflow.com/a/14842553).

**Comment by hashrock** [comment]
Thanks for letting me know! I learned a lot!
